# Site
name: "towards data"
title: "towards data"
description: "In towards data, we delve into a broad variety of data-related concepts, such as how to productively produce, manage, and democratize data. In all of our posts, we strive to provide you with sufficient information to grasp the concepts while also making them as simple to read as possible."
logo: 'assets/images/logo/logo_transparent.png'
favicon: 'assets/images/logo/logo_square_solid.png'
baseurl: ""
disqus: 'towardsdata'
mailchimp-list: 'https://gmail.us17.list-manage.com/subscribe?u=155954fdd35cc37fcbfab134a&id=acc42a78d4'
include: ["_pages"]
permalink: /:categories/:year/:title
email: hello@towardsdata.dev
contact-us: https://formspree.io/f/xdovkgjv
author: https://www.gravatar.com/avatar/6fc127cda8cd99830932538a58dc6173?s=250&d=mm&r=x

# Authors
authors:
  senthil:
    name: "Senthil Nayagan"
    display_name: "Senthil Nayagan"
    gravatar: 6fc127cda8cd99830932538a58dc6173
    email: "hello@senthilnayagan.com"
    web: https://senthilnayagan.com/
    twitter: https://twitter.com/SenthilNayagan
    mastodon: https://fosstodon.org/@towardsdata
    instagram: https://www.instagram.com/senthilnayagan
    description: "I am a Data Engineer by profession and a Rustacean by interest. Founder and Content Creator, <a href='https://towardsdata.dev' target='_blank'>towardsdata.dev</a>."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  #- flatify
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]